use std::fmt;
use std::str::FromStr;

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use validator::Validate;

use super::{DirectoryId, FeatureId, ProjectId, VersionId};

/// Controls the verbosity of guidance text for specs and architectural context.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum GuidanceLevel {
    Concise,
    #[default]
    Standard,
    Thorough,
}

/// Controls the output format of acceptance criteria generated by `/ac`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum AcFormat {
    /// `- [ ] Given/When/Then` checkbox format.
    #[default]
    Checkbox,
    /// Gherkin `Scenario:` / `Given` / `When` / `Then` format.
    Gherkin,
}

/// Controls the testing policy for a project.
///
/// Determines how aggressively Manifest nudges agents toward test-first
/// workflows. The policy is advisory — it never blocks feature completion.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum TestingPolicy {
    /// No testing guidance or nudging.
    None,
    /// Show testing guidance in `start_feature` but don't enforce.
    #[default]
    Advisory,
    /// Full TDD workflow: prompt for tests first, warn on unproven features.
    Tdd,
}

impl GuidanceLevel {
    pub fn as_str(&self) -> &'static str {
        match self {
            GuidanceLevel::Concise => "concise",
            GuidanceLevel::Standard => "standard",
            GuidanceLevel::Thorough => "thorough",
        }
    }
}

impl FromStr for GuidanceLevel {
    type Err = super::ParseEnumError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "concise" => Ok(Self::Concise),
            "standard" => Ok(Self::Standard),
            "thorough" => Ok(Self::Thorough),
            _ => Err(super::ParseEnumError(s.to_string())),
        }
    }
}

impl fmt::Display for GuidanceLevel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Serialize for GuidanceLevel {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for GuidanceLevel {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = String::deserialize(deserializer)?;
        GuidanceLevel::from_str(&s).map_err(serde::de::Error::custom)
    }
}

impl AcFormat {
    pub fn as_str(&self) -> &'static str {
        match self {
            AcFormat::Checkbox => "checkbox",
            AcFormat::Gherkin => "gherkin",
        }
    }
}

impl FromStr for AcFormat {
    type Err = super::ParseEnumError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "checkbox" => Ok(Self::Checkbox),
            "gherkin" => Ok(Self::Gherkin),
            _ => Err(super::ParseEnumError(s.to_string())),
        }
    }
}

impl fmt::Display for AcFormat {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Serialize for AcFormat {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for AcFormat {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = String::deserialize(deserializer)?;
        AcFormat::from_str(&s).map_err(serde::de::Error::custom)
    }
}

impl TestingPolicy {
    pub fn as_str(&self) -> &'static str {
        match self {
            TestingPolicy::None => "none",
            TestingPolicy::Advisory => "advisory",
            TestingPolicy::Tdd => "tdd",
        }
    }
}

impl FromStr for TestingPolicy {
    type Err = super::ParseEnumError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "none" => Ok(Self::None),
            "advisory" => Ok(Self::Advisory),
            "tdd" => Ok(Self::Tdd),
            _ => Err(super::ParseEnumError(s.to_string())),
        }
    }
}

impl fmt::Display for TestingPolicy {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Serialize for TestingPolicy {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for TestingPolicy {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let s = String::deserialize(deserializer)?;
        TestingPolicy::from_str(&s).map_err(serde::de::Error::custom)
    }
}

/// A project containing features.
///
/// Projects are the top-level organizational unit. Each project can have
/// multiple associated directories (e.g., frontend/backend repos) and
/// contains a tree of features describing its capabilities.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Project {
    pub id: ProjectId,
    /// URL-friendly identifier (e.g., "manifest", "rocketship"). Unique across all projects.
    pub slug: String,
    pub name: String,
    pub description: Option<String>,
    /// Project-wide instructions for AI agents (coding guidelines, conventions, etc.).
    pub instructions: Option<String>,
    /// The current/active version for this project (explicitly set by user).
    pub current_version_id: Option<VersionId>,
    /// The root feature for this project. All other features are descendants of this.
    /// The root feature's title = project name, details = project documentation,
    /// and its history tracks project-level events (version releases, etc.).
    pub root_feature_id: Option<FeatureId>,
    /// Where new features go by default: "backlog" (NULL version) or "next" (first unreleased).
    pub default_feature_destination: String,
    /// Controls verbosity of guidance for feature set / project-level details.
    pub detail_level: GuidanceLevel,
    /// Controls verbosity of guidance for leaf feature acceptance criteria.
    pub ac_level: GuidanceLevel,
    /// Controls the output format of acceptance criteria (`checkbox` or `gherkin`).
    pub ac_format: AcFormat,
    /// Controls the testing policy (`none`, `advisory`, or `tdd`).
    pub testing_policy: TestingPolicy,
    /// Test output adapter name (e.g., "cargo-test", "pytest"). When set, overrides auto-detection.
    pub test_adapter: Option<String>,
    /// Prefix for display IDs (e.g., "MAN" for MAN-42). Auto-derived from slug.
    pub key_prefix: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// A file system directory associated with a project.
///
/// Projects can span multiple directories (e.g., separate repos for frontend
/// and backend). One directory is marked as primary for default operations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectDirectory {
    pub id: DirectoryId,
    pub project_id: ProjectId,
    /// Absolute path to the directory on the local file system.
    pub path: String,
    /// Git remote URL (e.g., `git@github.com:org/repo.git`).
    pub git_remote: Option<String>,
    /// Whether this is the primary directory for the project.
    pub is_primary: bool,
    /// Directory-specific instructions for AI agents (build commands, test commands, etc.).
    pub instructions: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// Input for creating a new project.
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct CreateProjectInput {
    /// Display name for the project.
    #[validate(length(min = 1, max = 200))]
    pub name: String,
    /// URL-friendly identifier. If not provided, auto-generated from name.
    #[validate(length(max = 200))]
    pub slug: Option<String>,
    /// Brief description of the project's purpose.
    #[validate(length(max = 10_000))]
    pub description: Option<String>,
    /// Project-wide instructions for AI agents (coding guidelines, conventions, etc.).
    #[validate(length(max = 100_000))]
    pub instructions: Option<String>,
    /// Override the auto-derived key prefix for display IDs (e.g., "MAN").
    #[validate(length(max = 5))]
    pub key_prefix: Option<String>,
}

/// Input for updating an existing project. All fields are optional for partial updates.
#[derive(Debug, Clone, Default, Serialize, Deserialize, Validate)]
pub struct UpdateProjectInput {
    /// New display name for the project.
    #[validate(length(min = 1, max = 200))]
    pub name: Option<String>,
    /// URL-friendly identifier. Must be unique.
    #[validate(length(max = 200))]
    pub slug: Option<String>,
    /// Brief description of the project's purpose.
    #[validate(length(max = 10_000))]
    pub description: Option<String>,
    /// Project-wide instructions for AI agents (coding guidelines, conventions, etc.).
    #[validate(length(max = 100_000))]
    pub instructions: Option<String>,
    /// Set the current/active version for this project.
    pub current_version_id: Option<VersionId>,
    /// Where new features go by default: "backlog" or "next".
    pub default_feature_destination: Option<String>,
    /// Controls verbosity of guidance for feature set / project-level details.
    pub detail_level: Option<GuidanceLevel>,
    /// Controls verbosity of guidance for leaf feature acceptance criteria.
    pub ac_level: Option<GuidanceLevel>,
    /// Controls the output format of acceptance criteria (`checkbox` or `gherkin`).
    pub ac_format: Option<AcFormat>,
    /// Controls the testing policy (`none`, `advisory`, or `tdd`).
    pub testing_policy: Option<TestingPolicy>,
    /// Test output adapter name (e.g., "cargo-test", "pytest"). Overrides auto-detection.
    #[validate(length(max = 100))]
    pub test_adapter: Option<String>,
    /// Override the key prefix for display IDs (e.g., "MAN"). 2-5 uppercase letters.
    pub key_prefix: Option<String>,
}

/// Input for adding a directory to a project.
#[derive(Debug, Clone, Serialize, Deserialize, Validate)]
pub struct AddDirectoryInput {
    /// Absolute path to the directory on the local file system.
    #[validate(length(min = 1, max = 4_096))]
    pub path: String,
    /// Git remote URL (e.g., `git@github.com:org/repo.git`).
    #[validate(length(max = 1_000))]
    pub git_remote: Option<String>,
    /// Whether this is the primary directory for the project. Defaults to false.
    #[serde(default)]
    pub is_primary: bool,
    /// Directory-specific instructions for AI agents (build commands, test commands, etc.).
    #[validate(length(max = 10_000))]
    pub instructions: Option<String>,
}

/// Input for updating an existing directory. All fields are optional for partial updates.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateDirectoryInput {
    /// Absolute path to the directory on the local file system.
    pub path: Option<String>,
    /// Git remote URL (e.g., `git@github.com:org/repo.git`).
    pub git_remote: Option<String>,
    /// Whether this is the primary directory for the project.
    pub is_primary: Option<bool>,
    /// Directory-specific instructions for AI agents (build commands, test commands, etc.).
    pub instructions: Option<String>,
}

/// A project with its associated directories, used for detailed responses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectWithDirectories {
    #[serde(flatten)]
    pub project: Project,
    pub directories: Vec<ProjectDirectory>,
}
